In [1]:
import pandas as pd

In [2]:
info={
    "Name":["kiya","Ram"],
    "cgpa":[9,8]
}
df=pd.DataFrame(info)
print(df)

   Name  cgpa
0  kiya     9
1   Ram     8

In [3]:
df

   Name  cgpa
0  kiya     9
1   Ram     8

In [4]:
s=pd.Series([1,2,3,4,5,6])
print(s)
print(type(s))

#index based access
print(s[0])
print(s[2])

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
<class 'pandas.core.series.Series'>
1
3

In [5]:
#labelled based access
s=pd.Series([12,23,35], index=["adam","bob","charlie",])
print(s)
print(s["bob"])
print(s.index)

adam       12
bob        23
charlie    35
dtype: int64
23
Index(['adam', 'bob', 'charlie'], dtype='object')

In [6]:
#PROPERTIES OF SERIES
#series are homogenous--.dtype=obj
s=pd.Series([12,23,35,"abc"], index=["adam","bob","charlie",25])
print(s)

adam        12
bob         23
charlie     35
25         abc
dtype: object

In [7]:
#vectorized
s1=pd.Series([1,2,3,4,5])
s2=pd.Series([10,20,30,40,50])
print(s1+s2)

0    11
1    22
2    33
3    44
4    55
dtype: int64

In [8]:
#mutable values
s1=pd.Series([1,2,3,4,5])
s1[0]=100
print(s1)

0    100
1      2
2      3
3      4
4      5
dtype: int64

In [9]:
#immutable size
s1=pd.Series([1,2,3,4,5])
s1[0]=100
changed_s1=s1.drop(0)
print(s1)
print(changed_s1)

0    100
1      2
2      3
3      4
4      5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

In [10]:
# creating dataframe--->#dictionary

info={
    "Name":["Adam","bob","eve"],   
    "Age":[23,24,21],
    "gpa":[9,7,8]
}
df=pd.DataFrame(info)
print(df,type(df))
print(df.index)
print(df.columns)

   Name  Age  gpa
0  Adam   23    9
1   bob   24    7
2   eve   21    8 <class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'gpa'], dtype='object')

In [11]:
df

   Name  Age  gpa
0  Adam   23    9
1   bob   24    7
2   eve   21    8

In [12]:
#list of list
df=pd.DataFrame([["rk",23],["rahul",21],["charlie",21]], columns=["Name","Age"])
print(df)

      Name  Age
0       rk   23
1    rahul   21
2  charlie   21

In [13]:
#np array
import numpy as np
np_arr=np.array([[1,2,3],[4,5,6]])
df=pd.DataFrame(np_arr,columns=["A","B","C"])
print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [14]:
#csv data
df=pd.read_csv("employee_data.csv")
print(df,type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [15]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [16]:
#METHODS
df.head() #--->initial 5 rows

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

In [17]:
df.tail()

   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000

In [18]:
df.tail(2)

   ID   Name  Age Department  Salary
8   9    Ian   35         IT   75000
9  10  Julia   30    Finance   60000

In [19]:
df.sample()

   ID Name  Age Department  Salary
1   2  Bob   32         IT   72000

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

In [21]:
df.shape

(10, 5)

In [22]:
df.describe()

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [23]:
df.columns

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='object')

In [24]:
df.nunique()

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [25]:
#AQI data set
df=pd.read_csv("globalAirQuality.csv")
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [26]:
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [27]:
#selecting data --->cloumns
df[["city","aqi"]]

           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

In [28]:
#selcting rows --->rows
df.loc[0]

timestamp      2025-11-04 18:25:17.554219
country                                US
city                             New York
latitude                           40.713
longitude                         -74.006
pm25                               50.295
pm10                              108.938
no2                                27.998
so2                                 6.539
o3                                 52.568
co                                  1.096
aqi                                   108
temperature                        18.504
humidity                           70.168
wind_speed                          3.725
Name: 0, dtype: object

In [29]:
df.loc[1:3] #start idx:end idx(inclusive)

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956

In [30]:
df.iloc[3]
df.iloc[0:3] #start idx:end idx(exclusive)

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650

In [31]:
#for cells-->row,column(loc)
df.loc[0:3,["aqi","city"]]

   aqi      city
0  108  New York
1   90  New York
2   84  New York
3  158  New York

In [32]:
#(iloc)
df.iloc[0:3,2]

0    New York
1    New York
2    New York
Name: city, dtype: object

In [33]:
df.iloc[0:3,1:5]

  country      city  latitude  longitude
0      US  New York    40.713    -74.006
1      US  New York    40.713    -74.006
2      US  New York    40.713    -74.006

In [34]:
#for single cell
df.at[900,"city"]

'London'

In [35]:
df.iat[900,2]

'London'

In [36]:
#copy
cities=df["city"].copy()
cities[0]="mumbai"  #copy
print(cities)

0          mumbai
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: object

In [37]:
#filtering--->sq brakets
df[df["aqi"]>100]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
8,2025-11-05 02:25:17.554219,US,New York,40.713,-74.006,60.914,44.775,40.936,6.779,36.751,1.014,121,24.092,48.148,8.686
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17991,2025-11-19 09:25:17.554219,CH,Zurich,47.377,8.542,52.120,71.160,35.405,7.752,39.811,0.878,104,32.556,31.372,2.787
17993,2025-11-19 11:25:17.554219,CH,Zurich,47.377,8.542,76.613,37.495,29.662,5.419,57.042,1.103,153,20.437,79.602,2.663
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660

In [38]:
df[(df["aqi"]>100) & (df["temperature"]>30) ]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
14,2025-11-05 08:25:17.554219,US,New York,40.713,-74.006,38.815,121.394,25.969,4.112,44.730,1.124,121,34.481,81.790,3.576
17,2025-11-05 11:25:17.554219,US,New York,40.713,-74.006,63.552,57.838,13.754,4.427,42.251,0.997,127,36.193,62.906,7.097
25,2025-11-05 19:25:17.554219,US,New York,40.713,-74.006,56.954,75.045,29.837,9.541,54.198,1.170,113,31.289,43.279,5.264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17947,2025-11-17 13:25:17.554219,CH,Zurich,47.377,8.542,53.938,75.183,16.255,7.263,67.244,0.457,107,32.584,81.544,7.101
17950,2025-11-17 16:25:17.554219,CH,Zurich,47.377,8.542,70.255,60.620,32.081,2.065,47.803,0.852,140,36.885,34.173,1.748
17975,2025-11-18 17:25:17.554219,CH,Zurich,47.377,8.542,33.406,98.160,44.654,0.807,45.160,0.737,111,30.761,76.073,3.570
17976,2025-11-18 18:25:17.554219,CH,Zurich,47.377,8.542,73.493,89.558,9.313,4.768,51.505,0.745,146,30.909,81.573,1.024
17991,2025-11-19 09:25:17.554219,CH,Zurich,47.377,8.542,52.120,71.160,35.405,7.752,39.811,0.878,104,32.556,31.372,2.787

In [39]:
df[(df["aqi"]>100) & (df["temperature"]>30) ] [["city","aqi"]]

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]

In [40]:
#filtering data--->query method

df.query("aqi>100 & temperature>30 ") [["city","aqi"]]

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]

In [41]:
aqi_val=100
aqi_data =df.query("aqi> @aqi_val & temperature>30") [["city","aqi"]].copy()

In [42]:
aqi_data

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]

In [43]:
#CLEANING DATA--->handle missing values
df=pd.read_csv("raw_data.csv")
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [44]:
df.isnull()

       id   name    age  country  gender  income
0   False  False  False    False   False   False
1   False  False  False    False   False   False
2   False  False   True    False   False   False
3   False  False   True    False   False   False
4   False  False  False    False   False    True
5   False  False  False    False   False   False
6   False   True  False    False   False   False
7   False  False  False     True   False   False
8   False  False  False    False   False   False
9   False  False   True    False   False   False
10  False  False  False    False    True   False

In [45]:
#count no of missing value
df.isnull().sum()

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [46]:
#droping rows with null value
df.dropna()

   id        name   age country  gender   income
0   1    John Doe  29.0     USA    Male  55000.0
1   1    John Doe  29.0     USA    Male  55000.0
5   5      Li Wei  27.0   China    Male  51000.0
8   8  Rachel Lee  29.0     USA  Female  62000.0

In [47]:
#droping columns with null value
df.dropna(axis=1)

    id
0    1
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10

In [48]:
#filling missing value
df.fillna(0)

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   0.0  Canada   Female  62000.0
3    3          Alex   0.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      0.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6             0  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0       0     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   0.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA        0  58000.0

In [49]:
#missing mean value with mean of the data
age_mean=df["age"].mean()

df["age"].fillna(age_mean)

0     29.00
1     29.00
2     32.75
3     32.75
4     34.00
5     27.00
6     45.00
7     38.00
8     29.00
9     32.75
10    31.00
Name: age, dtype: float64

In [50]:
#for storing this value:(making copy of orginal data)
cleaned_data=df.copy()
age_mean=cleaned_data["age"].mean()
cleaned_data["age"]=cleaned_data["age"].fillna(age_mean)
cleaned_data

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [51]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [52]:
#forward fill copy upper data
df.ffill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  29.0  Canada   Female  62000.0
3    3          Alex  29.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  47000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6        Li Wei  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0   India     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  29.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA     Male  58000.0

In [53]:
#backward fill-copy lower data
df.bfill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [54]:
#Handle duplicates--->checking
df.duplicated()

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [55]:
df[["country","gender"]].duplicated()

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [56]:
#for droping duplicates
df.drop_duplicates()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [57]:
df2=df.copy()
df2.drop_duplicates(inplace=True)
df2

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [58]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [59]:
#Data types and date-time
df.dtypes

id           int64
name        object
age        float64
country     object
gender      object
income     float64
dtype: object

In [60]:
df2=df.copy()
df2=df2.fillna(0)
df2["age"]=df2["age"].astype("int64").copy()
df2.dtypes

id           int64
name        object
age          int64
country     object
gender      object
income     float64
dtype: object

In [61]:
#date-time data
aqi_data=pd.read_csv("globalAirQuality.csv")
aqi_data["timestamp"]=pd.to_datetime(aqi_data["timestamp"])
aqi_data["timestamp"].dtype

dtype('<M8[ns]')

In [62]:
date_str=pd.Series([pd.to_datetime("2026-12-31")])
type(date_str.dtypes)

numpy.dtypes.DateTime64DType

In [63]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [64]:
#handles string
df["gender"].str.lower()

0        male
1        male
2      female
3     unknown
4      female
5        male
6      female
7        male
8      female
9        male
10        NaN
Name: gender, dtype: object

In [65]:
df["gender"].str.upper()

0        MALE
1        MALE
2      FEMALE
3     UNKNOWN
4      FEMALE
5        MALE
6      FEMALE
7        MALE
8      FEMALE
9        MALE
10        NaN
Name: gender, dtype: object

In [66]:
df["gender"].str.capitalize()

0        Male
1        Male
2      Female
3     Unknown
4      Female
5        Male
6      Female
7        Male
8      Female
9        Male
10        NaN
Name: gender, dtype: object

In [67]:
df["name"].str.split(" ")

0         [John, Doe]
1         [John, Doe]
2       [Jane, Smith]
3              [Alex]
4     [Maria, Garcia]
5           [Li, Wei]
6                 NaN
7       [Ahmed, Khan]
8       [Rachel, Lee]
9      [Carlos, Ruiz]
10     [Emily, Davis]
Name: name, dtype: object

In [68]:
df["country"].str.contains("india",case=False)

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object

In [69]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [70]:
#TRANSFORMING DATA-FEATURE EXTRACTION--->apply fnx(high order fnx)
df2=df.copy()
df2["tax"]=df2["income"].apply(lambda x:"20%" if x>=60 else "10%")
df2

    id          name   age country   gender   income  tax
0    1      John Doe  29.0     USA     Male  55000.0  20%
1    1      John Doe  29.0     USA     Male  55000.0  20%
2    2    Jane Smith   NaN  Canada   Female  62000.0  20%
3    3          Alex   NaN     USA  Unknown  47000.0  20%
4    4  Maria Garcia  34.0   Spain   Female      NaN  10%
5    5        Li Wei  27.0   China     Male  51000.0  20%
6    6           NaN  45.0   India   Female  73000.0  20%
7    7    Ahmed Khan  38.0     NaN     Male  68000.0  20%
8    8    Rachel Lee  29.0     USA   Female  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0  20%
10  10   Emily Davis  31.0     USA      NaN  58000.0  20%

In [71]:
#map()
gender_map={"Male":"M","Female":"F","Unknown":"U"}
df2["gender"]=df2["gender"].map(gender_map)
df2

    id          name   age country gender   income  tax
0    1      John Doe  29.0     USA      M  55000.0  20%
1    1      John Doe  29.0     USA      M  55000.0  20%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
3    3          Alex   NaN     USA      U  47000.0  20%
4    4  Maria Garcia  34.0   Spain      F      NaN  10%
5    5        Li Wei  27.0   China      M  51000.0  20%
6    6           NaN  45.0   India      F  73000.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
8    8    Rachel Lee  29.0     USA      F  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  20%
10  10   Emily Davis  31.0     USA    NaN  58000.0  20%

In [72]:
#assign()
df2=df2.assign(newincome=df2["income"]*1.1)

In [73]:
#replace
df2["country"]=df2["country"].replace("USA","US")
df2

    id          name   age country gender   income  tax  newincome
0    1      John Doe  29.0      US      M  55000.0  20%    60500.0
1    1      John Doe  29.0      US      M  55000.0  20%    60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%    68200.0
3    3          Alex   NaN      US      U  47000.0  20%    51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%        NaN
5    5        Li Wei  27.0   China      M  51000.0  20%    56100.0
6    6           NaN  45.0   India      F  73000.0  20%    80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%    74800.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%    68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  20%    49500.0
10  10   Emily Davis  31.0      US    NaN  58000.0  20%    63800.0

In [74]:
#rename--->column,rows
df2.columns=["ID","Name","Age","Country","Gender","Income","Tax","New_Income"]
df2.rename(columns={"Income":"Salaray"})
df2.rename(index={1:"First"})

       ID          Name   Age Country Gender   Income  Tax  New_Income
0       1      John Doe  29.0      US      M  55000.0  20%     60500.0
First   1      John Doe  29.0      US      M  55000.0  20%     60500.0
2       2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3       3          Alex   NaN      US      U  47000.0  20%     51700.0
4       4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5       5        Li Wei  27.0   China      M  51000.0  20%     56100.0
6       6           NaN  45.0   India      F  73000.0  20%     80300.0
7       7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8       8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
9       9   Carlos Ruiz   NaN  Mexico      M  45000.0  20%     49500.0
10     10   Emily Davis  31.0      US    NaN  58000.0  20%     63800.0

In [75]:
#sort values-->ascending
df2=df2.fillna(50)
sorted_df=df2.sort_values(["Income","Age"])  #here sorting will be done based on income only but only if income is same i will be done based on age in  that case

In [76]:
#sort values-->desending
df2.sort_values("Income",ascending=False)

    ID          Name   Age Country Gender   Income  Tax  New_Income
6    6            50  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0      50      M  68000.0  20%     74800.0
2    2    Jane Smith  50.0  Canada      F  62000.0  20%     68200.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
10  10   Emily Davis  31.0      US     50  58000.0  20%     63800.0
0    1      John Doe  29.0      US      M  55000.0  20%     60500.0
1    1      John Doe  29.0      US      M  55000.0  20%     60500.0
5    5        Li Wei  27.0   China      M  51000.0  20%     56100.0
3    3          Alex  50.0      US      U  47000.0  20%     51700.0
9    9   Carlos Ruiz  50.0  Mexico      M  45000.0  20%     49500.0
4    4  Maria Garcia  34.0   Spain      F     50.0  10%        50.0

In [77]:
#sort index
sorted_df.sort_index()

    ID          Name   Age Country Gender   Income  Tax  New_Income
0    1      John Doe  29.0      US      M  55000.0  20%     60500.0
1    1      John Doe  29.0      US      M  55000.0  20%     60500.0
2    2    Jane Smith  50.0  Canada      F  62000.0  20%     68200.0
3    3          Alex  50.0      US      U  47000.0  20%     51700.0
4    4  Maria Garcia  34.0   Spain      F     50.0  10%        50.0
5    5        Li Wei  27.0   China      M  51000.0  20%     56100.0
6    6            50  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0      50      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
9    9   Carlos Ruiz  50.0  Mexico      M  45000.0  20%     49500.0
10  10   Emily Davis  31.0      US     50  58000.0  20%     63800.0

In [78]:
#reset index
sorted_df.reset_index()

    index  ID          Name   Age Country Gender   Income  Tax  New_Income
0       4   4  Maria Garcia  34.0   Spain      F     50.0  10%        50.0
1       9   9   Carlos Ruiz  50.0  Mexico      M  45000.0  20%     49500.0
2       3   3          Alex  50.0      US      U  47000.0  20%     51700.0
3       5   5        Li Wei  27.0   China      M  51000.0  20%     56100.0
4       0   1      John Doe  29.0      US      M  55000.0  20%     60500.0
5       1   1      John Doe  29.0      US      M  55000.0  20%     60500.0
6      10  10   Emily Davis  31.0      US     50  58000.0  20%     63800.0
7       8   8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
8       2   2    Jane Smith  50.0  Canada      F  62000.0  20%     68200.0
9       7   7    Ahmed Khan  38.0      50      M  68000.0  20%     74800.0
10      6   6            50  45.0   India      F  73000.0  20%     80300.0

In [79]:
# for droping the preserved labelled value---> (drop=True)
sorted_df.reset_index(drop=True)

    ID          Name   Age Country Gender   Income  Tax  New_Income
0    4  Maria Garcia  34.0   Spain      F     50.0  10%        50.0
1    9   Carlos Ruiz  50.0  Mexico      M  45000.0  20%     49500.0
2    3          Alex  50.0      US      U  47000.0  20%     51700.0
3    5        Li Wei  27.0   China      M  51000.0  20%     56100.0
4    1      John Doe  29.0      US      M  55000.0  20%     60500.0
5    1      John Doe  29.0      US      M  55000.0  20%     60500.0
6   10   Emily Davis  31.0      US     50  58000.0  20%     63800.0
7    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
8    2    Jane Smith  50.0  Canada      F  62000.0  20%     68200.0
9    7    Ahmed Khan  38.0      50      M  68000.0  20%     74800.0
10   6            50  45.0   India      F  73000.0  20%     80300.0

In [80]:
#ranking
sorted_df["Ranking"]=sorted_df["Income"].rank(ascending=False,method="dense")
sorted_df

    ID          Name   Age Country Gender   Income  Tax  New_Income  Ranking
4    4  Maria Garcia  34.0   Spain      F     50.0  10%        50.0      9.0
9    9   Carlos Ruiz  50.0  Mexico      M  45000.0  20%     49500.0      8.0
3    3          Alex  50.0      US      U  47000.0  20%     51700.0      7.0
5    5        Li Wei  27.0   China      M  51000.0  20%     56100.0      6.0
0    1      John Doe  29.0      US      M  55000.0  20%     60500.0      5.0
1    1      John Doe  29.0      US      M  55000.0  20%     60500.0      5.0
10  10   Emily Davis  31.0      US     50  58000.0  20%     63800.0      4.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0      3.0
2    2    Jane Smith  50.0  Canada      F  62000.0  20%     68200.0      3.0
7    7    Ahmed Khan  38.0      50      M  68000.0  20%     74800.0      2.0
6    6            50  45.0   India      F  73000.0  20%     80300.0      1.0

In [81]:
#reorder column -->simply write how you want
sorted_df[["ID","Name","Age","Country","Gender","Income","New_Income","Tax"]]

    ID          Name   Age Country Gender   Income  New_Income  Tax
4    4  Maria Garcia  34.0   Spain      F     50.0        50.0  10%
9    9   Carlos Ruiz  50.0  Mexico      M  45000.0     49500.0  20%
3    3          Alex  50.0      US      U  47000.0     51700.0  20%
5    5        Li Wei  27.0   China      M  51000.0     56100.0  20%
0    1      John Doe  29.0      US      M  55000.0     60500.0  20%
1    1      John Doe  29.0      US      M  55000.0     60500.0  20%
10  10   Emily Davis  31.0      US     50  58000.0     63800.0  20%
8    8    Rachel Lee  29.0      US      F  62000.0     68200.0  20%
2    2    Jane Smith  50.0  Canada      F  62000.0     68200.0  20%
7    7    Ahmed Khan  38.0      50      M  68000.0     74800.0  20%
6    6            50  45.0   India      F  73000.0     80300.0  20%

In [82]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [83]:
#ques-shift id column to the end in df--->my way   
df[["name",	"age","country"	,"gender","income","id"]]

            name   age country   gender   income  id
0       John Doe  29.0     USA     Male  55000.0   1
1       John Doe  29.0     USA     Male  55000.0   1
2     Jane Smith   NaN  Canada   Female  62000.0   2
3           Alex   NaN     USA  Unknown  47000.0   3
4   Maria Garcia  34.0   Spain   Female      NaN   4
5         Li Wei  27.0   China     Male  51000.0   5
6            NaN  45.0   India   Female  73000.0   6
7     Ahmed Khan  38.0     NaN     Male  68000.0   7
8     Rachel Lee  29.0     USA   Female  62000.0   8
9    Carlos Ruiz   NaN  Mexico     Male  45000.0   9
10   Emily Davis  31.0     USA      NaN  58000.0  10

In [84]:
#ques-shift id column to the end in df-->using list comprehension
df3=df.copy()
new_col_order=[col for col in df3.columns if col!="id"]+["id"]
df3[new_col_order]

            name   age country   gender   income  id
0       John Doe  29.0     USA     Male  55000.0   1
1       John Doe  29.0     USA     Male  55000.0   1
2     Jane Smith   NaN  Canada   Female  62000.0   2
3           Alex   NaN     USA  Unknown  47000.0   3
4   Maria Garcia  34.0   Spain   Female      NaN   4
5         Li Wei  27.0   China     Male  51000.0   5
6            NaN  45.0   India   Female  73000.0   6
7     Ahmed Khan  38.0     NaN     Male  68000.0   7
8     Rachel Lee  29.0     USA   Female  62000.0   8
9    Carlos Ruiz   NaN  Mexico     Male  45000.0   9
10   Emily Davis  31.0     USA      NaN  58000.0  10

In [85]:
#writing data to csv-->first cleaning it and using to_csv
df2=df.copy()
df2=df2.drop_duplicates()
df2=df2.fillna(0)
df2=df2.sort_values("income")
df2=df2.reset_index(drop=True)
df2.to_csv("sorted_data.csv")

In [86]:
#GROUPING AND AGGREGATION IN DATA-->groupby() and mean/max/min
df.groupby("country")["income"].mean()

country
Canada    62000.0
China     51000.0
India     73000.0
Mexico    45000.0
Spain         NaN
USA       55400.0
Name: income, dtype: float64

In [87]:
df.groupby("country")["income"].max()

country
Canada    62000.0
China     51000.0
India     73000.0
Mexico    45000.0
Spain         NaN
USA       62000.0
Name: income, dtype: float64

In [88]:
df.groupby("country")["income"].min()

country
Canada    62000.0
China     51000.0
India     73000.0
Mexico    45000.0
Spain         NaN
USA       47000.0
Name: income, dtype: float64

In [89]:
df.groupby("gender")["income"].mean()

gender
Female     65666.666667
Male       54800.000000
Unknown    47000.000000
Name: income, dtype: float64

In [90]:
df.groupby("gender")["income"].max()

gender
Female     73000.0
Male       68000.0
Unknown    47000.0
Name: income, dtype: float64

In [91]:
#using agg() or aggregate()
df.groupby("country")["income"].agg(["mean","max","min"])

            mean      max      min
country
Canada   62000.0  62000.0  62000.0
China    51000.0  51000.0  51000.0
India    73000.0  73000.0  73000.0
Mexico   45000.0  45000.0  45000.0
Spain        NaN      NaN      NaN
USA      55400.0  62000.0  47000.0

In [92]:
#column renaming in agg()
df.groupby("country")["income"].agg(avg_income="mean",max_income="max",min_income="min")

         avg_income  max_income  min_income
country
Canada      62000.0     62000.0     62000.0
China       51000.0     51000.0     51000.0
India       73000.0     73000.0     73000.0
Mexico      45000.0     45000.0     45000.0
Spain           NaN         NaN         NaN
USA         55400.0     62000.0     47000.0

In [93]:
df.groupby("country").agg({
    "income":"mean",
     "age":"mean"
})

          income   age
country
Canada   62000.0   NaN
China    51000.0  27.0
India    73000.0  45.0
Mexico   45000.0   NaN
Spain        NaN  34.0
USA      55400.0  29.5

In [94]:
df.groupby("country").agg({
    "income":"mean",
     "age":"max"
})

          income   age
country
Canada   62000.0   NaN
China    51000.0  27.0
India    73000.0  45.0
Mexico   45000.0   NaN
Spain        NaN  34.0
USA      55400.0  31.0

In [95]:
df.groupby("country").agg(
avg_income =("income","mean"),
max_age=("age","max")
)

         avg_income  max_age
country
Canada      62000.0      NaN
China       51000.0     27.0
India       73000.0     45.0
Mexico      45000.0      NaN
Spain           NaN     34.0
USA         55400.0     31.0

In [96]:
#melt
df=pd.DataFrame({
    "country":["USA","USA","India","India"],
    "year":[2020,2021,2020,2021],
    "sales":[100,120,90,110],
    "profit":[20,25,18,22],
    "tax":[20,30,40,50]
})
df

  country  year  sales  profit  tax
0     USA  2020    100      20   20
1     USA  2021    120      25   30
2   India  2020     90      18   40
3   India  2021    110      22   50

In [97]:
melted_df=df.melt(
    id_vars=["country","year"],
    value_vars=["sales","profit","tax"],
    var_name="metrics",
    value_name ="value"
)
melted_df

   country  year metrics  value
0      USA  2020   sales    100
1      USA  2021   sales    120
2    India  2020   sales     90
3    India  2021   sales    110
4      USA  2020  profit     20
5      USA  2021  profit     25
6    India  2020  profit     18
7    India  2021  profit     22
8      USA  2020     tax     20
9      USA  2021     tax     30
10   India  2020     tax     40
11   India  2021     tax     50

In [98]:
#PIVOT
df=pd.DataFrame({
    "country":["USA","USA","India","India"],
    "year":[2020,2021,2020,2021],
    "sales":[100,120,90,110],
    "profit":[20,25,18,22],
   
})
df

  country  year  sales  profit
0     USA  2020    100      20
1     USA  2021    120      25
2   India  2020     90      18
3   India  2021    110      22

In [99]:
melted_df=df.melt(
    id_vars=["country","year"],
    value_vars=["sales","profit"],
    var_name="metrics",
    value_name ="value"
)
melted_df

  country  year metrics  value
0     USA  2020   sales    100
1     USA  2021   sales    120
2   India  2020   sales     90
3   India  2021   sales    110
4     USA  2020  profit     20
5     USA  2021  profit     25
6   India  2020  profit     18
7   India  2021  profit     22

In [100]:
melted_df.pivot(
    index=["country","year"],
    columns="metrics",
    values="value"
)

metrics       profit  sales
country year
India   2020      18     90
        2021      22    110
USA     2020      20    100
        2021      25    120

In [101]:
#basic visualisation--->hist(),plot()
df=pd.read_csv("employee_data.csv")
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [102]:
#df["Age"].hist()

In [103]:
#df.plot(kind="scatter",x="Age",y="Salaray"

In [104]:
#merging and joining data
df_customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "name": ["Adam", "Bob", "Charlie", "Dave"]
})

df_orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104],
    "customer_id": [2, 1, 4, 5],
    "amount": [250, 120, 300, 180]
})

In [105]:
df_customers

   customer_id     name
0            1     Adam
1            2      Bob
2            3  Charlie
3            4     Dave

In [106]:
df_orders

   order_id  customer_id  amount
0       101            2     250
1       102            1     120
2       103            4     300
3       104            5     180

In [107]:
#inner join---> only common data
pd.merge(df_customers,df_orders ,on ="customer_id")

   customer_id  name  order_id  amount
0            1  Adam       102     120
1            2   Bob       101     250
2            4  Dave       103     300

In [108]:
#left join---> keeps df_customers values as it was left 
pd.merge(df_customers,df_orders ,on ="customer_id", how="left")

   customer_id     name  order_id  amount
0            1     Adam     102.0   120.0
1            2      Bob     101.0   250.0
2            3  Charlie       NaN     NaN
3            4     Dave     103.0   300.0

In [109]:
#right join--->keeps df_orders values as it was right
pd.merge(df_customers,df_orders ,on ="customer_id", how="right")

   customer_id  name  order_id  amount
0            2   Bob       101     250
1            1  Adam       102     120
2            4  Dave       103     300
3            5   NaN       104     180

In [110]:
#outer join--->all data of both
pd.merge(df_customers,df_orders ,on ="customer_id",how="outer")

   customer_id     name  order_id  amount
0            1     Adam     102.0   120.0
1            2      Bob     101.0   250.0
2            3  Charlie       NaN     NaN
3            4     Dave     103.0   300.0
4            5      NaN     104.0   180.0

In [111]:
#concatenation
df1 = pd.DataFrame({
    "id": [1, 2, 3],
    "name": ["Adam", "Eve", "Bob"]
})

df2 = pd.DataFrame({
    "id": [4, 5, 6],
    "name": ["Charlie", "Fester", "Gilian"]
})

In [112]:
df1

   id  name
0   1  Adam
1   2   Eve
2   3   Bob

In [113]:
df2

   id     name
0   4  Charlie
1   5   Fester
2   6   Gilian

In [114]:
#row
pd.concat([df1,df2])

   id     name
0   1     Adam
1   2      Eve
2   3      Bob
0   4  Charlie
1   5   Fester
2   6   Gilian

In [115]:
#sorting index for row concat
pd.concat([df1,df2],ignore_index=True)

   id     name
0   1     Adam
1   2      Eve
2   3      Bob
3   4  Charlie
4   5   Fester
5   6   Gilian

In [116]:
#column concat
pd.concat([df1,df2],axis=1)

   id  name  id     name
0   1  Adam   4  Charlie
1   2   Eve   5   Fester
2   3   Bob   6   Gilian